[env:yd-esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.variant = esp32s3
board_build.usb_mode = otg
framework = arduino

; --- Arduino IDE: CPU Frequency "240MHz (WiFi)" ---
board_build.f_cpu = 240000000L

; --- Arduino IDE: Flash Mode "QIO 120MHz" ---
board_build.flash_mode = qio
board_build.f_flash = 80000000L ; PlatformIO'da genelde 80MHz en stabilidir, 120 zorlayabilir

; --- Arduino IDE: Flash Size "16MB" & Partition Scheme ---
board_upload.flash_size = 16MB
; Görselde 4MB partition seçili ama kartın 16MB. Eyudio için 16MB'ı kullanalım:
board_build.partitions = default_16MB.csv

; --- Arduino IDE: PSRAM "OPI PSRAM" ---
board_build.arduino.memory_type = qio_opi ; QIO Flash + OPI PSRAM
board_build.psram = opi

; --- Arduino IDE: USB CDC On Boot & Mode ---
build_unflags = -std=gnu++11
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
    -DCORE_DEBUG_LEVEL=3
    -DconfigUSE_TRACE_FACILITY=1
    -DconfigUSE_STATS_FORMATTING_FUNCTIONS=1
    -DDEBUG_ESP_HTTPCLIENT=0
    -DDEBUG_ESP_WIFI=0
    -DDEBUG_ESP_HTTP_SERVER=0
    -std=gnu++2a
    -Isrc/doom
    -IEyudio-Private/include
    -DCONFIG_LWIP_TCP_WND_DEFAULT=65535
    -DCONFIG_LWIP_TCP_RECVMBOX_SIZE=32
    -DCONFIG_LWIP_UDP_RECVMBOX_SIZE=16
    -DCONFIG_LWIP_TCPIP_RECVMBOX_SIZE=32
    -DCONFIG_LWIP_TCP_SND_BUF_DEFAULT=65535
    -DCONFIG_LWIP_TCP_WND=65535
    -O3
    -ffast-math
    -DHW_ESP32

; sdkconfig.defaults: CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=y ve diğer IDF ayarları
board_build.sdkconfig = sdkconfig.defaults

; --- Kütüphaneler ---
lib_deps =
    https://github.com/bitluni/ESP32-S3-VGA.git
    h2zero/NimBLE-Arduino@^1.4.1
    adafruit/Adafruit GFX Library
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson
    https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6
    bitbank2/unzipLIB @ 1.0.0
    ricmoo/QRCode@^0.0.1

; --- Upload & Monitor ---
upload_speed = 921600
monitor_speed = 115200